repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        language: system
        entry: python ./scripts/run-clang-format.py -r
        files: \.(ino|cpp|h)$
