language: c
os: linux
dist: xenial

cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

git:
  depth: false
  quiet: true

branches:
  except:
  - gh-pages

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - python3-pip
      - python3-wheel
      - clang-format-5.0

env:
  global:
     - PRETTYNAME="DSUL - Nano"

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
   - curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/run-clang-format.py > run-clang-format.py

install:
   - arduino --install-library "Adafruit NeoPixel"

script:
   - python run-clang-format.py -r .
   - build_platform uno
   - build_platform leonardo
   - build_platform mega2560
   - build_platform zero
   - build_platform trinket_m0
   - build_platform metro_m4
   - build_platform esp8266

after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
