name: Build
run-name: ${{ github.actor }} is building and testing dsul-arduino

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.sh"
      - "**.yaml"
  pull_request:
    branches:
      - main
      - "feature/*"
    paths-ignore:
      - "**.md"
      - "**.sh"
      - "**.yaml"
  workflow_dispatch:

env:
  SKETCHES_REPORTS_PATH: sketches-reports
  SKETCHES_REPORTS_ARTIFACT_NAME: sketches-reports

jobs:
  build:
    name: Build DSUL
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        fqbn:
          - arduino:avr:uno
          - arduino:avr:leonardo
          - arduino:avr:mega
          - arduino:avr:nano
          - arduino:mbed_rp2040:pico
          - arduino:dsmf:arduino_zero_native
          - esp8266:esp8266:generic
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          enable-deltas-report: true
          sketch-paths: |
            - dsul
          libraries: |
            - name: "Adafruit_NeoPixel"
      - name: Upload build reports
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}

  report:
    name: Create reports
    needs: build
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request'
    steps:
      - name: Download sketches reports artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
      - name: Create reports
        uses: arduino/report-size-deltas@v1
        with:
          sketches-reports-source: ${{ env.SKETCHES_REPORTS_PATH }}
